### ISSUE TITLE
Add new documentation for array

### ISSUE THREAD

**Issue by manh9203** [kuzudb/kuzu-docs#102]
Since we are moving from FIXED_LIST to ARRAY and adding more vector operations for it, we should have a separate documentation page for ARRAY data type.

Note: This issue should be addressed after #103 is merged and the new version is released.

**Comment by prrao87** [comment]
@manh9203 could you make a note of this and not make any commits until I have the chance to get #103 reviewed? There's a major refactor ongoing to the docs.

**Comment by prrao87** [comment]
@manh9203 here's the current state of the `LIST` types (fixed and var lists):

**Comment by prrao87** [comment]
@manh9203 here's the latest docs for the `FIXED-LIST` and `VAR-LIST` data types.

Per this issue, do you think the `FIXED-LIST` should be removed from this section and we should add a new type called `ARRAY` instead? Or is there a deprecation period where both are active?

**Comment by manh9203** [comment]
@prrao87 We replaced ```FIXED-LIST``` by ```ARRAY``` in our nightly build, but it's not available on ```v0.3.2``` yet, so I think we can still keep the docs as it is and add some notes about this. 
We are also adding new functions for ```ARRAY``` and rename ```VAR_LIST``` to ```LIST```, so in the next release, we should have a separate section for ```ARRAY``` and its functions.

**Comment by prrao87** [comment]
Ok, will reach out to Guodong once it's released.

**Comment by prrao87** [comment]
Fixed in #128.
