### ISSUE TITLE
Add missing statements to testing framework docs

### ISSUE THREAD

**Issue by prrao87** [kuzudb/kuzu-docs#111]
The following statements in the [testing framework docs](https://docs.kuzudb.com/developer-guide/testing-framework/) are undocumented:

- `RELOADDB`
- `IMPORT_DATABASE`
- `REMOVE_FILE`

These need to be added when possible.

Related to #97.

**Comment by ray6080** [comment]
@hououou should be able to handle these.

**Comment by prrao87** [comment]
Done in #114
