### ISSUE TITLE
Add documentation for MAP data type

### ISSUE THREAD

**Issue by ray6080** [kuzudb/kuzu-docs#152]
MAP is supported but missed in doc's data type page.

**Comment by prrao87** [comment]
@ray6080 Could you point me to the tests for the map function? I wasn't able to locate it in the source. Or, maybe someone else could post example snippets that we could add to the data types page in the docs. Let me know either way.

**Comment by ray6080** [comment]
Sorry missed the comment here 😅. I think @acquamarin is the best to provide examples and draft doc, as he implemented this data type, so you can review and edit further.

**Comment by acquamarin** [comment]
I think we do have doc for MAP datatype but somehow it doesn't show up on our doc website:
https://github.com/kuzudb/kuzu-docs/blob/main/src/content/docs/cypher/data-types/map.md

**Comment by prrao87** [comment]
Done in #203.
