### ISSUE TITLE
Document keywords and whether or not they're reserved

### ISSUE THREAD

**Issue by mxwli** [kuzudb/kuzu-docs#155]
As of [3626](https://github.com/kuzudb/kuzu/pull/3626), we've decided that the keyword list should be documented, as well as whether or not each keyword is reserved. Additionally, we should document whether or not the status of the keyword complies with whether or not it's reserved in Postgres. In the following table, NA means the keyword doesn't exist in PG.
|Keyword|Status|Complies with PG?|
|-|-|-|
|ADD|Not Reserved|Complies|
|ALL|Reserved|Complies|
|ALTER|Not Reserved|Complies|
|AND|Reserved|Complies|
|ASCENDING|Reserved|NA|
|ASC|Reserved|Does Not Comply|
|AS|Not Reserved|Complies|
|ATTACH|Not Reserved|Complies|
|BEGIN|Not Reserved|Complies|
|BY|Not Reserved|Complies|
|CALL|Not Reserved|Complies|
|CASE|Reserved|Complies|
|CAST|Reserved|Complies|
|COLUMN|Reserved|Complies|
|COMMENT|Not Reserved|Complies|
|COMMIT\_SKIP\_CHECKPOINT|Reserved|NA|
|COMMIT|Not Reserved|Complies|
|CONTAINS|Not Reserved|NA|
|COPY|Not Reserved|Complies|
|COUNT|Not Reserved|NA|
|CREATE|Reserved|Complies|
|CYCLE|Not Reserved|Complies|
|DATABASE|Not Reserved|Complies|
|DBTYPE|Reserved|NA|
|DECIMAL|Not Reserved|Complies|
|DEFAULT|Reserved|Complies|
|DELETE|Not Reserved|Complies|
|DESCENDING|Reserved|NA|
|DESC|Reserved|Complies|
|DETACH|Not Reserved|Complies|
|DISTINCT|Reserved|Complies|
|DROP|Not Reserved|Complies|
|ELSE|Reserved|Complies|
|END|Reserved|Complies|
|ENDS|Reserved|NA|
|EXISTS|Reserved|NA|
|EXPLAIN|Not Reserved|Complies|
|EXPORT|Not Reserved|NA|
|EXTENSION|Not Reserved|Complies|
|FALSE|Reserved|Complies|
|FROM|Reserved|Complies|
|GLOB|Reserved|NA|
|GRAPH|Not Reserved|NA|
|GROUP|Reserved|Complies|
|HEADERS|Reserved|NA|
|IF|Not Reserved|Complies|
|IMPORT|Not Reserved|Complies|
|INCREMENT|Not Reserved|Complies|
|IN|Reserved|Complies|
|INSTALL|Reserved|NA|
|IS|Reserved|NA|
|KEY|Not Reserved|Complies|
|LIMIT|Reserved|Complies|
|LOAD|Not Reserved|Complies|
|MACRO|Reserved|NA|
|MATCH|Not Reserved|Complies|
|MAXVALUE|Not Reserved|Complies|
|MERGE|Not Reserved|Complies|
|MINVALUE|Not Reserved|Complies|
|NODE|Not Reserved|NA|
|NOT|Reserved|Complies|
|NO|Not Reserved|Complies|
|NULL|Reserved|NA|
|ONLY|Reserved|Complies|
|ON|Reserved|Complies|
|OPTIONAL|Reserved|NA|
|ORDER|Reserved|Complies|
|OR|Reserved|Complies|
|PRIMARY|Reserved|Complies|
|PROFILE|Reserved|NA|
|PROJECT|Not Reserved|Complies|
|RDFGRAPH|Reserved|NA|
|READ|Not Reserved|Complies|
|REL|Not Reserved|NA|
|RENAME|Not Reserved|Complies|
|RETURN|Not Reserved|Complies|
|ROLLBACK\_SKIP\_CHECKPOINT|Reserved|NA|
|ROLLBACK|Not Reserved|Complies|
|SEQUENCE|Not Reserved|Complies|
|SET|Not Reserved|Complies|
|SHORTEST|Reserved|NA|
|STARTS|Reserved|AN|
|START|Not Reserved|Complies|
|TABLE|Reserved|Complies|
|THEN|Reserved|Complies|
|TO|Reserved|Complies|
|TRANSACTION|Not Reserved|Complies|
|TRUE|Reserved|Complies|
|TYPE|Not Reserved|Complies|
|UNION|Reserved|Complies|
|UNWIND|Reserved|NA|
|USE|Not Reserved|NA|
|WHEN|Reserved|Complies|
|WHERE|Reserved|Complies|
|WITH|Reserved|Complies|
|WRITE|Not Reserved|Complies|
|XOR|Reserved|NA|

plaintext for the markdown table can be accessed by editing this issue.

**Comment by prrao87** [comment]
@andyfengHKU this would go in the [Cypher manual](https://docs.kuzudb.com/cypher/), correct? Trying to think of which page exactly it would fit best.

**Comment by andyfengHKU** [comment]
I think so. You can make the final call here.

**Comment by prrao87** [comment]
Placing this on hold till we can clarify the intent behind this internally.
