### ISSUE TITLE
Suggestion: Add a doc page on known issues

### ISSUE THREAD

**Issue by ray6080** [kuzudb/kuzu-docs#172]
There are some known issues in the system that won't be address in the near future.

An example is https://github.com/kuzudb/kuzu/issues/3002, which is due to bugs in third party lib. We'd better document it in our docs before we can resolve it.

Keeping a list here for suggestions:
- [x] ~~https://github.com/kuzudb/kuzu/issues/3002.~~ (no longer an issue)
- [x] Explorer not able to auto reflect newly changes from other processes.
- [x] Not able to limit concurrent read/write connections within the same process https://github.com/kuzudb/kuzu/issues/3295

**Comment by prrao87** [comment]
Updated in 0.5.0 docs.
