### ISSUE TITLE
Document how to use `UNWIND` followed by `WHERE` clause

### ISSUE THREAD

**Issue by acquamarin** [kuzudb/kuzu-docs#268]
We currrently don't support using unwind parameters directly in the where clause:
For example:
```
match (n:Item) unwind n.descriptions as desc where size(desc) < 25 return descq
```
is not allowed.
The user should use a with clause in such case:
```
match (n:Item) unwind n.descriptions as desc with desc where size(desc) < 25 return descq
```

**Comment by prrao87** [comment]
Sounds good, will take a look as to where this fits in and update 👍🏽
