### ISSUE TITLE
Document how to use `COPY` into a subset of table columns from an input file

### ISSUE THREAD

**Issue by ray6080** [kuzudb/kuzu-docs#272]
We support copy from source into only a subset of table columns, but didn't get documented somehow. 

For example, we have a csv file `partial_person.csv` of three columns: id, name, and age. We want to copy into a table with four columns. It can be done in the following way.
```
CREATE NODE TABLE Person(id INT64, name STRING, age INT64, address STRING, PRIMARY KEY(id));
COPY Person(id, name, age) FROM 'partial_person.csv'
```

**Comment by prrao87** [comment]
This is an important one - I had NO idea about it, so I presume no other user did, too 😅
