### ISSUE TITLE
Clarify the intent of a specific form of `EXISTS` query

### ISSUE THREAD

**Issue by prrao87** [kuzudb/kuzu-docs#312]
We need to document the meaning of this query:
```cypher
MATCH (a2:Account) WHERE (a2)-[e:Transfer]->(a1:Account)<-[:Owns]-(p1:Person {name : "George"}) RETURN a2
```

This query compiles and runs without issues. But we do not document this way of using `WHERE` anywhere (it's different than our way of using `WHERE EXISTS`.

**Comment by prrao87** [comment]
@andyfengHKU Is the above query a variant of the `WHERE EXISTS` query? Is this just syntax sugar where the `EXISTS` keyword is optional? Or is there a difference in the semantics when we do `WHERE EXISTS`?

**Comment by andyfengHKU** [comment]
Hi @prrao87 this is a variant of WHERE EXISTS
