### ISSUE TITLE
Add images to all blogs with light (not transparent background)

### ISSUE THREAD

**Issue by prrao87** [kuzudb/kuzu-docs#64]
Docusaurus offers a dark mode which a lot of people use to read long-form text. In all our upcoming blogs, we should ensure to export images with a light background rather than a transparent background, so that images are more easily visible.

@semihsalihoglu-uw This might be too much work to update all images at this point, but the [RAG](https://kuzudb.com/docusaurus/blog/llms-graphs-part-2) posts in dark mode show images that appear like this. Could you maybe change your default export settings to light for upcoming images?

![image](https://github.com/kuzudb/kuzu-docs/assets/35005448/5cadd120-9dc0-4feb-b8ef-3da2ffde921e)

**Comment by mewim** [comment]
This might be achieved by adding a CSS override for all images without the necessity to reprocess all images. I'll look into it some time.

**Comment by prrao87** [comment]
@mewim is it possible to do this for PNGs (which all these images are right now)? I thought it's possible only for SVGs.

**Comment by mewim** [comment]
<img width="1192" alt="Screenshot 2024-01-26 at 11 14 05 PM" src="https://github.com/kuzudb/kuzu-docs/assets/14037726/b14ec5d8-96c9-4506-a3c3-2952bcc3ef5a">

**Comment by prrao87** [comment]
Excellent! Please push the fix when you can 🙏🏽

**Comment by mewim** [comment]
I have pushed it. Feel free to merge it whenever you like.
