### ISSUE TITLE
[Testing Framework] Clean up stale descriptions and miss newly added statements

### ISSUE THREAD

**Issue by ray6080** [kuzudb/kuzu-docs#97]
State descriptions:
1. For [convert to parquet](https://docs.kuzudb.com/developer-guide/testing-framework/#converting-csv-to-parquet). The note below is stale now.
```
Note: for the conversion, the framework does not match the current schema to the parquet files. It relies on arrow to auto detect the datatype when reading and convering the CSV to Parquet.
```
2. `BEGIN_WRITE_TRANSACTION` should be removed. No longer useful as we have cypher statements for starting a write transaction.

Missing statements:
- `RELOADDB`
- `IMPORT_DATABASE`
-  `REMOVE_FILE`

**Comment by prrao87** [comment]
@ray6080 feel free to assign the right person to update the docs with the missing statements.

**Comment by ray6080** [comment]
@hououou should be able to handle `BEGIN_WRITE_TRANSACTION` and missing statements.

I'm leaving converting to parquet part to Manh.
